### ISSUE TITLE
Disable stripping of tags

### ISSUE THREAD

**Issue by Elwood-P** [adobe-webplatform/balance-text#57]
I have text with words highlighted using em tags. Is there any way to stop balance-text stripping the tags?

**Comment by redmunds** [comment]
@Elwood-P That should be fixed in the latest version (1.4).

Are you using a [CDN](https://github.com/adobe-webplatform/balance-text#use-from-a-cdn) ? Those are still using 1.3 (only because I haven't found time to update them). You can use a local version for now.

Otherwise, please provide an example that's broken in v1.4.

**Comment by Elwood-P** [comment]
Thank you! Exactly as you say I was using 1.3 from the CDN. 1.4 does not strip the tags. 

Appreciate your help and the great plugin :)

**Comment by redmunds** [comment]
Closing.

**Comment by nunoneves** [comment]
Hi! You forgot to tag the latest code with 1.4 so that there's a published version.

**Comment by redmunds** [comment]
@nunoneves Thanks for the reminder. Latest code tagged as v1.4.0: https://github.com/adobe-webplatform/balance-text/releases/tag/v1.4.0

**Comment by redmunds** [comment]
@nunoneves I discovered that I wasn't setup for auto-update. Latest version is now published:

* https://cdnjs.cloudflare.com/ajax/libs/balance-text/1.6.0/jquery.balancetext.min.js
* https://cdn.jsdelivr.net/jquery.balancetext/1.6.0/jquery.balancetext.min.js
